import Head from 'next/head';

import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App Esteban</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <code className={styles.code}>Crud TODO list</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By Esteban
            </a>
          </div>
        </div>

        <form className={styles.center}>
          <label htmlFor="">New task</label>
          <input type="text" name="" id="" />
          <button type="submit">Add</button>
        </form>

        <div className={styles.center}>
          <ul>
            <li style={{ listStyle: 'none' }}>
              <input type="checkbox" name="" id="" style={{ marginRight: 8 }} />
              <label htmlFor="">Task 1</label>
              <p>Descriptiuon</p>
            </li>
          </ul>
        </div>

        {/* <div className={styles.grid}></div> */}
      </main>
    </>
  );
}
